#!/bin/sh
LANG=C
LC_TIME=C
export LANG
export LC_TIME
VERSION="`cat VERSION`"
GITID="`git show|awk '{print $2;exit}'`"
CC="`sed -e '/^CC=/!d' -e 's,^CC=,,' makefile`"
CFLAGS="`sed -e '/^CFLAGS=/!d' -e 's,^CFLAGS=,,' makefile`"
DATE="`date`"
cat <<EOF
// generated by 'mkversion.sh'
#include "headers.h"
const char * get_version () {
  return "$VERSION" " " "$GITID";
}
void print_version () {
  msg (1, "Version %s", get_version ());
  msg (1, "Compiled $CC $CFLAGS");
  msg (1, "Date $DATE");
}
EOF
