#!/bin/sh
LANG=C
LC_TIME=C
export LANG
export LC_TIME
VERSION="`cat VERSION`"
GITID="`git show|awk '{print $2;exit}'`"
CC="`sed -e '/^CC=/!d' -e 's,^CC=,,' makefile`"
CFLAGS="`sed -e '/^CFLAGS=/!d' -e 's,^CFLAGS=,,' makefile`"
RELEASED="`git log -n 1|sed -e '/^Date:/!d' -e 's,^Date: *,,'`"
COMPILED="`date`"
SYSTEM="`uname -srmn`"
cat <<EOF
// generated by 'version.sh'
#include "headers.h"
const char * get_version () {
  return "$VERSION $GITID";
}
void print_version () {
  msg (1, "Version %s", get_version ());
  msg (1, "Released $RELEASED");
  msg (1, "Compiled $COMPILED");
  msg (1, "System $SYSTEM");
  msg (1, "Compiler $CC $CFLAGS");
}
EOF
